import type { LibraryData, PlaylistInfo, TrackRecord, TransitionRecord } from '../types'

const tracks: TrackRecord[] = [
  {
    id: 't-001',
    title: 'Night Notes',
    artist: 'Skonoks',
    bpm: 125,
    rating: 3,
    camelotKey: '4A',
    rawKey: null,
    path: '/mock/night-notes.wav',
    playlists: ['p-1'],
  },
  {
    id: 't-002',
    title: 'Another Round (Jay Strata rmx)',
    artist: 'Skonoks',
    bpm: 129,
    rating: 3,
    camelotKey: '4A',
    rawKey: null,
    path: '/mock/another-round-jay-strata-rmx.wav',
    playlists: ['p-1'],
  },
  {
    id: 't-003',
    title: 'Til I Get You (Skonoks Remix)',
    artist: 'CLVPS',
    bpm: 126,
    rating: 3,
    camelotKey: '4A',
    rawKey: null,
    path: '/mock/til-i-get-you-skonoks-remix.wav',
    playlists: ['p-1', 'p-3'],
  },
  {
    id: 't-004',
    title: '5 Carnian Pluvial Episode (DX-9 under water rmx)',
    artist: 'Skonoks',
    bpm: 127,
    rating: 3,
    camelotKey: '5A',
    rawKey: null,
    path: '/mock/5-carnian-pluvial-episode-dx-9-under-water-rmx.wav',
    playlists: ['p-1'],
  },
  {
    id: 't-005',
    title: 'Another Round (Skonoks 4:4 Mix)',
    artist: 'Skonoks',
    bpm: 126,
    rating: 3,
    camelotKey: '5A',
    rawKey: null,
    path: '/mock/another-round-skonoks-4-4-mix.wav',
    playlists: ['p-1'],
  },
  {
    id: 't-006',
    title: 'Warm Embrace',
    artist: 'Skonoks',
    bpm: 126,
    rating: 3,
    camelotKey: '6A',
    rawKey: null,
    path: '/mock/warm-embrace.wav',
    playlists: ['p-1'],
  },
  {
    id: 't-007',
    title: 'Crystals',
    artist: 'Skonoks',
    bpm: 125,
    rating: 3,
    camelotKey: '6A',
    rawKey: null,
    path: '/mock/crystals.wav',
    playlists: ['p-1'],
  },
  {
    id: 't-008',
    title: 'Scatter Plot',
    artist: 'Skonoks',
    bpm: 125,
    rating: 3,
    camelotKey: '7B',
    rawKey: null,
    path: '/mock/scatter-plot.wav',
    playlists: ['p-1'],
  },
  {
    id: 't-009',
    title: 'Oh hey',
    artist: 'Skonoks',
    bpm: 125,
    rating: 3,
    camelotKey: '8A',
    rawKey: null,
    path: '/mock/oh-hey.wav',
    playlists: ['p-1', 'p-3'],
  },
  {
    id: 't-010',
    title: 'Fours',
    artist: 'Skonoks',
    bpm: 125,
    rating: null,
    camelotKey: '12A',
    rawKey: null,
    path: '/mock/fours.wav',
    playlists: ['p-1', 'p-4'],
  },
  {
    id: 't-011',
    title: 'Threes',
    artist: 'Skonoks',
    bpm: 125,
    rating: null,
    camelotKey: '12A',
    rawKey: null,
    path: '/mock/threes.wav',
    playlists: ['p-1', 'p-4'],
  },
  {
    id: 't-012',
    title: 'Out There',
    artist: 'Skonoks',
    bpm: 125,
    rating: null,
    camelotKey: '6A',
    rawKey: null,
    path: '/mock/out-there.wav',
    playlists: ['p-1'],
  },
  {
    id: 't-013',
    title: 'Pocket Riot',
    artist: 'Skonoks',
    bpm: 126,
    rating: null,
    camelotKey: '3A',
    rawKey: null,
    path: '/mock/pocket-riot.wav',
    playlists: ['p-1'],
  },
  {
    id: 't-014',
    title: 'Crossing The Valley',
    artist: 'Skonoks',
    bpm: 125,
    rating: null,
    camelotKey: '7A',
    rawKey: null,
    path: '/mock/crossing-the-valley.wav',
    playlists: ['p-1'],
  },
  {
    id: 't-015',
    title: 'Baseline Test',
    artist: 'Skonoks',
    bpm: 126,
    rating: 3,
    camelotKey: '12A',
    rawKey: null,
    path: '/mock/baseline-test.wav',
    playlists: ['p-2'],
  },
  {
    id: 't-016',
    title: 'Supercritical',
    artist: 'Skonoks',
    bpm: 126,
    rating: 3,
    camelotKey: '5A',
    rawKey: null,
    path: '/mock/supercritical.aiff',
    playlists: ['p-2'],
  },
  {
    id: 't-017',
    title: "That Dot, That's Us!",
    artist: 'Skonoks',
    bpm: 124,
    rating: 3,
    camelotKey: '6A',
    rawKey: null,
    path: '/mock/that-dot-thats-us.aiff',
    playlists: ['p-2'],
  },
  {
    id: 't-018',
    title: 'See What Comes',
    artist: 'Skonoks',
    bpm: 125,
    rating: 3,
    camelotKey: '9A',
    rawKey: null,
    path: '/mock/see-what-comes.aiff',
    playlists: ['p-2', 'p-5'],
  },
  {
    id: 't-019',
    title: 'Ascending Glow',
    artist: 'Skonoks',
    bpm: 125,
    rating: 3,
    camelotKey: '10A',
    rawKey: null,
    path: '/mock/ascending-glow.aiff',
    playlists: ['p-2'],
  },
  {
    id: 't-020',
    title: 'Try Me',
    artist: 'Skonoks',
    bpm: 125,
    rating: 3,
    camelotKey: '3B',
    rawKey: null,
    path: '/mock/try-me.aiff',
    playlists: ['p-2'],
  },
  {
    id: 't-021',
    title: 'Tapa Ono',
    artist: 'Skonoks',
    bpm: 124,
    rating: 3,
    camelotKey: '8B',
    rawKey: null,
    path: '/mock/tapa-ono.aiff',
    playlists: ['p-2'],
  },
  {
    id: 't-022',
    title: 'Resonating Fabric',
    artist: 'Skonoks',
    bpm: 126,
    rating: 3,
    camelotKey: '5A',
    rawKey: null,
    path: '/mock/resonating-fabric.aiff',
    playlists: ['p-2'],
  },
  {
    id: 't-023',
    title: 'Flyswatter 2025',
    artist: 'Skonoks',
    bpm: 127,
    rating: 3,
    camelotKey: '5A',
    rawKey: null,
    path: '/mock/flyswatter-2025.aiff',
    playlists: ['p-2'],
  },
  {
    id: 't-024',
    title: 'Machine Without Purpose',
    artist: 'Skonoks',
    bpm: 125,
    rating: 3,
    camelotKey: '6A',
    rawKey: null,
    path: '/mock/machine-without-purpose.aiff',
    playlists: ['p-2'],
  },
]

const playlists: PlaylistInfo[] = [
  {
    id: 'p-1',
    name: 'Skonoks — 2024 selections',
    trackIds: [
      't-001',
      't-002',
      't-003',
      't-004',
      't-005',
      't-006',
      't-007',
      't-008',
      't-009',
      't-010',
      't-011',
      't-012',
      't-013',
      't-014',
    ],
  },
  {
    id: 'p-2',
    name: 'Skonoks — 2025 releases',
    trackIds: ['t-015', 't-016', 't-017', 't-018', 't-019', 't-020', 't-021', 't-022', 't-023', 't-024'],
  },
  {
    id: 'p-3',
    name: 'North-South Connection EP',
    trackIds: ['t-003', 't-009'],
  },
  {
    id: 'p-4',
    name: 'Threes or Fours',
    trackIds: ['t-010', 't-011'],
  },
  {
    id: 'p-5',
    name: 'See What Comes',
    trackIds: ['t-018'],
  },
]

const transitions: TransitionRecord[] = playlists.flatMap((playlist) => {
  return playlist.trackIds.slice(0, -1).map((trackId, index) => {
    const fromTrack = tracks.find((track) => track.id === trackId)
    const toTrack = tracks.find((track) => track.id === playlist.trackIds[index + 1])

    if (!fromTrack || !toTrack) {
      throw new Error('Mock playlist references an unknown track.')
    }

    return {
      playlistId: playlist.id,
      playlistName: playlist.name,
      fromTrackId: fromTrack.id,
      toTrackId: toTrack.id,
      fromKey: fromTrack.camelotKey,
      toKey: toTrack.camelotKey,
      fromBpm: fromTrack.bpm,
      toBpm: toTrack.bpm,
    }
  })
})

export function createMockLibrary(): LibraryData {
  return {
    source: 'mock',
    sourceName: 'Mock DJ crate',
    tracks,
    playlists,
    transitions,
  }
}
